package org.ssssssss.magicapi.utils;

import org.ssssssss.script.MagicScript;
import org.ssssssss.script.MagicScriptContext;
import org.ssssssss.script.MagicScriptDebugContext;
import org.ssssssss.script.annotation.Comment;

import java.util.Map;

/**
 * 脚本管理
 *
 * @author peter
 */
public class ScriptManager {

	private static final String EXPRESSION_PREFIX = "/* generated by execute expression */ return ";

	@Comment("执行原始脚本代码\n\n"
            + "这是最基础的脚本执行方法，直接执行传入的脚本内容\n\n"
            + "@param script 要执行的脚本代码字符串\n\n"
            + "@param context 脚本执行上下文对象，包含变量绑定等信息\n\n"
            + "@return 脚本执行后的返回结果\n\n"
            + "@example\n"
            + "MagicScriptContext context = new MagicScriptContext();\n"
            + "context.setVariable(\"name\", \"张三\");\n"
            + "Object result = ScriptManager.executeScript(\"'你好 ' + name\", context);\n"
            + "// 返回: \"你好 张三\"")
	public static Object executeScript(String script, MagicScriptContext context) {
		script = (context instanceof MagicScriptDebugContext ? MagicScript.DEBUG_MARK : "") + script;
		MagicScript magicScript = MagicScript.create(script, null);
		// 执行脚本
		return magicScript.execute(context);
	}

	 @Comment("执行表达式（自动添加return语句包装）\n\n"
	            + "将普通表达式包装成完整的脚本语句执行，适合简单的单行表达式计算\n\n"
	            + "@param script 要执行的表达式字符串\n\n"
	            + "@param context 脚本执行上下文对象\n\n"
	            + "@return 表达式计算结果\n\n"
	            + "@example\n"
	            + "MagicScriptContext context = new MagicScriptContext();\n"
	            + "context.setVariable(\"x\", 5);\n"
	            + "context.setVariable(\"y\", 10);\n"
	            + "Object result = ScriptManager.executeExpression(\"x + y\", context);\n"
	            + "// 返回: 15")
	public static Object executeExpression(String script, MagicScriptContext context) {
		return executeScript(EXPRESSION_PREFIX + script, context);
	}

	 @Comment("执行表达式（使用Map传参的简便方法）\n\n"
	            + "快速创建执行上下文并执行表达式的便捷方法，适合简单场景\n\n"
	            + "@param script 要执行的表达式字符串\n\n"
	            + "@param paramMap 参数键值对，key为变量名，value为变量值\n\n"
	            + "@return 表达式计算结果\n\n"
	            + "@example\n"
	            + "Map<String, Object> params = new HashMap<>();\n"
	            + "params.put(\"a\", 20);\n"
	            + "params.put(\"b\", 30);\n"
	            + "Object result = ScriptManager.executeExpression(\"a * b\", params);\n"
	            + "// 返回: 600")
	public static Object executeExpression(String script, Map<String, Object> paramMap) {
		return executeExpression(script, new MagicScriptContext(paramMap));
	}
}
